# Generated by Django 4.1.3 on 2023-02-21 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillmatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('mechanic', 'Mecánico'), ('scientific', 'Científico'), ('persuasive', 'Persuasivo'), ('artistic', 'Artístico'), ('calculus', 'Cálculo')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='KuderTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='artistic',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='calculus',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='done_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mechanic',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='persuasive',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='scientific',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='ActivityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillmatch.kudertest')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=999)),
                ('activity_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillmatch.activitygroup')),
                ('negative', models.ManyToManyField(related_name='negative_interest', to='skillmatch.interestarea')),
                ('positive', models.ManyToManyField(related_name='positive_interest', to='skillmatch.interestarea')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='onprogress_projects',
            field=models.ManyToManyField(related_name='user_onprogress', to='skillmatch.project'),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_projects',
            field=models.ManyToManyField(related_name='user_pendings', to='skillmatch.project'),
        ),
        migrations.AddField(
            model_name='user',
            name='previous_projects',
            field=models.ManyToManyField(related_name='user_previous', to='skillmatch.project'),
        ),
    ]
