# Generated by Django 4.1.3 on 2023-03-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillmatch', '0002_interestarea_kudertest_project_user_artistic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='details',
            new_name='courses',
        ),
        migrations.AddField(
            model_name='project',
            name='instructions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='introduction',
            field=models.TextField(default=''),
        ),
    ]
