# Generated by Django 4.1.3 on 2023-03-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillmatch', '0003_rename_details_project_courses_project_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='instructions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='introduction',
            field=models.TextField(),
        ),
    ]
