# Generated by Django 4.1.3 on 2023-03-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillmatch', '0007_alter_project_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='artistic',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='calculus',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='mechanic',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='persuasive',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='scientific',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, default=None, max_length=500),
        ),
    ]
