# Generated by Django 4.1.3 on 2023-03-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillmatch', '0008_project_artistic_project_calculus_project_mechanic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_url',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images/'),
        ),
    ]
