# Generated by Django 4.1.3 on 2023-03-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillmatch', '0010_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='abilities',
            field=models.ManyToManyField(blank=True, to='skillmatch.ability'),
        ),
        migrations.AddField(
            model_name='project',
            name='careers',
            field=models.ManyToManyField(blank=True, to='skillmatch.career'),
        ),
    ]
