# Generated by Django 4.1.3 on 2023-03-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillmatch', '0011_ability_career_project_abilities_project_careers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ability',
            old_name='ability',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='career',
            old_name='career',
            new_name='name',
        ),
    ]
