# Generated by Django 4.1.3 on 2023-04-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillmatch', '0018_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked_projects',
            field=models.ManyToManyField(blank=True, related_name='user_liked', to='skillmatch.project'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved_projects',
            field=models.ManyToManyField(blank=True, related_name='user_pendings', to='skillmatch.project'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher'), ('admin', 'admin')], default='Student', max_length=8),
        ),
    ]
