# Generated by Django 4.1.3 on 2023-04-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillmatch', '0019_project_pending_alter_user_liked_projects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
