# Generated by Django 4.1.3 on 2023-04-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillmatch', '0020_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='ability',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='career',
            name='career',
            field=models.CharField(max_length=20),
        ),
    ]
