# Generated by Django 4.1.3 on 2023-04-17 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillmatch', '0022_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='likes',
        ),
    ]
